### ISSUE TITLE
Question about ceviche-challenges module and parameters which defines fabrication constrains in the paper are missing?

### ISSUE THREAD

**Issue by GitHubOpenIssue** [google/ceviche-challenges#2]
Hello,

In the presentation, it is confirmed: "The code in this module was used to produce the results in the [Inverse Design of Photonic Devices with Strict Foundry Fabrication Constraints] paper."

The thing is taking in account for the example "waveguide bend" as its explained in "Usage" section, the objects overrides design parameters but Fabrication Constraint parameters are not inputs for simulations and I don't know how to make the inverse design of one of this results that's shown in the paper. If it is possible can you illustrate us with a full example for "waveguide bend" for example? (I remark if it is possible)

It is the loaded parameter for simulation, there are others for fabrication constrains, where are they?? the code is full to got results in the paper?

> def waveguide_bend_2umx2um_spec(**overrides) -> spec.WaveguideBendSpec:
>   """Design spec for a waveguide bend with a 2 um x 2 um design region."""
>   defaults = spec.WaveguideBendSpec(
>       wg_width=200 * u.nm,
>       wg_length=750 * u.nm,
>       wg_mode_padding=750 * u.nm,
>       padding=400 * u.nm,
>       port_pml_offset=50 * u.nm,
>       variable_region_size=(2000 * u.nm, 2000 * u.nm),
>       cladding_permittivity=1.0,
>       slab_permittivity=12.25,
>       input_monitor_offset=50 * u.nm,
>       pml_width=20,
>   )
>   return dataclasses.replace(defaults, **overrides)
> 
> def waveguide_bend_sim_params(**overrides) -> params.CevicheSimParams:
>   """Simulation parameters appropriate for the waveguide bend."""
>   defaults = params.CevicheSimParams(
>       resolution=50 * u.nm,
>       wavelengths=u.Array([1550.], u.nm),
>   )
>   return dataclasses.replace(defaults, **overrides)

I'm waiting for replaying and thanks in advance,

**Comment by ianwilliamson** [comment]
The code in this module was used to parameterize and setup the challenge problems used in the paper. These challenge problems accept designs from an optimizer and enable gradients to be calculated. This module does _not_ include any optimizers or design constraints. It is on the user to set that up and to perform an optimization.

**Comment by GitHubOpenIssue** [comment]
With the present module is it possible to get the results shown in the paper?

**Comment by GitHubOpenIssue** [comment]
Well sorry I thing is not
