### ISSUE TITLE
Convenience Functions?

### ISSUE THREAD

**Issue by jan-david-fischbach** [google/ceviche-challenges#3]
The readme states 
> There are a number of other features in the device model class, such as returning an image of the structure. These features are best explored by reading the code and the function docstrings, as we don't have comprehensive standalone documentation at this time.

I have been going through the code and was not able to identify functions used to plot the simulations/structures. 
Maybe you can point me in the right direction?

**Comment by ianwilliamson** [comment]
The `Model` class has a density method:

https://github.com/google/ceviche-challenges/blob/6731eac81baca696192624b55a51db9b03de9bcf/ceviche_challenges/model_base.py#L216-L217
 
It returns an image array that one could pass to Matplotlib's `imshow()` or `pcolor()` functions. The simulator outputs are scattering parameters and fields:

https://github.com/google/ceviche-challenges/blob/6731eac81baca696192624b55a51db9b03de9bcf/ceviche_challenges/model_base.py#L89-L119

These arrays can also be plotted through Matplotlib.

Hope this helps.

**Comment by jan-david-fischbach** [comment]
Thanks,
I had seen those but thought I might have missed something else.
Thanks for the quick and thorough response!
