### ISSUE TITLE
Loss functions

### ISSUE THREAD

**Issue by teytaud** [google/ceviche-challenges#8]
Thanks for sharing this code.

On the github site, we can read the following loss for Bend:

=========
import autograd
import autograd.numpy as npa

def loss_fn(x):
  """A simple loss function taking mean s11 - mean s21."""
  s_params, _ = model.simulate(x)
  s11 = npa.abs(s_params[:, 0, 0])
  s21 = npa.abs(s_params[:, 0, 1])
  return npa.mean(s11) - npa.mean(s21)

=========

This is very useful, as we can see the loss function for Bend as a function of the output "s_params" of model.simulate(x).

Would you have a similar loss function for the other benchmarks, namely mode converter, wdm, splitter ? This would be helpful as a groundtruth for comparing different approaches.

Also why using "mean" ? s11, in this case, is a scalar, not an array, so this looks useless ? 

Thanks for any comment.

**Comment by ianwilliamson** [comment]
> Would you have a similar loss function for the other benchmarks, namely mode converter, wdm, splitter ? This would be helpful as a groundtruth for comparing different approaches.

You could try using the loss functions in the referenced paper.

> Also why using "mean" ? s11, in this case, is a scalar, not an array, so this looks useless ?

Generally the challenges will return scattering parameters calculated across multiple wavelengths. The `:` in the expression `s_params[:, 0, 0]` leaves this wavelength dimension and the mean reduces across that dimension.
